import type { NextPage } from "next";
import Head from "next/head";
import Option from "../components/Option";
import Map from "../components/Map";

const Home: NextPage = () => {
  return (
    <div className="flex flex-col h-screen mx-auto sm:max-w-xl sm:px-24 md:max-w-3xl md:px-32">
      <Head>
        <title>Uber 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="h-2/5 w-full">
        <Map />
      </section>
      <section className="h-3/5 w-full border-t mt-16 border-gray-300 ">
        <Option />
      </section>
    </div>
  );
};

export default Home;
