import type { NextPage } from "next";
import Head from "next/head";
import Choice from "../components/Choice";
import Map from "../components/Map";

const Home: NextPage = () => {
  return (
    <div className="flex flex-col h-screen mx-auto max-w-3xl">
      <Head>
        <title>Uber 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Map />
      <Choice />
    </div>
  );
};

export default Home;
